name: Deploy All

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip all lambdas
        run: |
          zip -r get_all_inventory_items.zip lambda/get_all_inventory_items
          zip -r get_inventory_item.zip lambda/get_inventory_item
          zip -r add_inventory_item.zip lambda/add_inventory_item
          zip -r delete_inventory_item.zip lambda/delete_inventory_item
          zip -r get_location_inventory_items.zip lambda/get_location_inventory_items

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy Lambdas
        run: |
          aws lambda update-function-code --function-name get_all_inventory_items --zip-file fileb://get_all_inventory_items.zip
          aws lambda update-function-code --function-name get_inventory_item --zip-file fileb://get_inventory_item.zip
          aws lambda update-function-code --function-name add_inventory_item --zip-file fileb://add_inventory_item.zip
          aws lambda update-function-code --function-name delete_inventory_item --zip-file fileb://delete_inventory_item.zip
          aws lambda update-function-code --function-name get_location_inventory_items --zip-file fileb://get_location_inventory_items.zip